### ISSUE TITLE
Add ctrl+z undo functionality for clipboard pasting

### ISSUE THREAD

**Issue by buddyp450** [ag-grid/ag-grid-enterprise#106]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently with range selection enabled, it's possible to copy a few cells across and then attempt to paste into a new row and they paste downward in a column format rather than rows.

**Expected behavior**
If copying horizontally, should paste horizontally.

**Minimal reproduction of the problem with instructions**
Try it on the examples

**What is the motivation / use case for changing the behavior?**
I didn't mind so much the way it pasted, just that it overwrote my pre-existing data with no way to restore and if I am copying a lot of data this can overwrite a lot of data with no way to undo.

**Comment by buddyp450** [comment]
Realizing after posting this that part of my issue was I was using ctrl+click to select ranges, so that's a separate issue

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
