### ISSUE TITLE
Global search with regular expressions

### ISSUE THREAD

**Issue by Lucasvo1** [ag-grid/ag-grid-enterprise#107]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a global filter input, one cannot use regular expressions. 

**Expected behavior**
It would be nice if the user could enter some kind of basic regular expression in an input which would filter the table.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.

**Comment by didje251** [comment]
Can we re-open this request? I would like to know if there is any way to add regular-expression handling into the filters ?

**Comment by pbb72** [comment]
I haven't tried it yet, but I guess this is possible already using a custom filter: https://ag-grid.com/javascript-data-grid/filter-custom/
