### ISSUE TITLE
[filter group] Selecting a group ignores the quickFilterText

### ISSUE THREAD

**Issue by gabrielenosso** [ag-grid/ag-grid-enterprise#11]
Hi, I don't know if it is the proper behavior, but when you select a group with   groupSelectsChildren = true, it ignores the quickFilterText.

So if I have a group with 30 rows, but I filter it and it shows only 6 of them, and then I click on the checkbox to select the group, it selects all of them instead of selecting only the ones that it shows.

It looks strange, particularly because the group rows are showing in parenthesis the number of items which they have, which is updated (it is "6")

![selection problem wit grouopd](https://cloud.githubusercontent.com/assets/4018887/14890240/19aa333e-0d62-11e6-986f-3e840fa530ae.png)

**Comment by ceolter** [comment]
tracked by AG-184
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi,

This should be fixed in our latest release 13.3.0
