### ISSUE TITLE
RangeController.prototype.removeRange = function (rangeSelection) {...}

### ISSUE THREAD

**Issue by zealoushacker** [ag-grid/ag-grid-enterprise#119]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently it seems impossible to remove a *selected* range programmatically via the API, without writing a custom function to traverse and filter the `api.rangeController.cellRanges` or without first invoking `clearRangeSelection`, maintaining internal state of previous selections, and then forcing reselection of all ranges except the one that the user wants to exclude via `addRange`. 

**Expected behavior**

It would be great to be able to call a function on the api to remove a specific range that had been previously selected via `RangeController.prototype.removeRange = function (rangeSelection) {...}`, where `rangeSelection` would be similar or identical to the one passed via `addRange`.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I am writing specific column-selection functionality. In other words, a user should be able to select a column for inclusion, and then deselect it should they want to change their mind. While it seems like I could write a function to accomplish this result, it is logical to expect functionality to reverse selection of a range. While I could maintain my own internal state of selected ranges, invoke `clearRangeSelection`, and then apply all remaining ranges via `addRange`, this seems like a huge duplication of work and items in memory.

**Please tell us about your environment:**

macOS Sierra 10.12.4 (16E195), vim, yarn, webpack, react

* **ag-Grid-Enterprise version:** 
9.0.1 (npm)

* **Browser:**
all

* **Language:**
all

**Comment by zealoushacker** [comment]
Is my report effectively a duplicate of https://github.com/ceolter/ag-grid/issues/1367

**Comment by zealoushacker** [comment]
FWIW, I was able to accomplish this via something like this in our react app:

```
+                if (this.state.checked[params.column.getId()]) {
 -                  rowStart: 0,		 +                  this.api.addRangeSelection({
 -                  rowEnd: this.state.rowData.length - 1,		 +                    rowStart: 0,
 -                  columnStart: params.column.getId(),		 +                    rowEnd: this.state.rowData.length - 1,
 -                  columnEnd: params.column.getId(),		 +                    columnStart: params.column.getId(),
 -                });		 +                    columnEnd: params.column.getId(),
 +                  });
 +                } else {
 +                  remove(this.api.rangeController.cellRanges, (r) => {
 +                    return r.start.column.colId === params.column.getId() && 
 +                      r.end.column.colId === params.column.getId() &&
 +                      r.start.rowIndex === 0 &&
 +                      r.end.rowIndex === this.state.rowData.length - 1
 +                  });
 +                  this.api.rangeController.dispatchChangedEvent(true, false);
 +                }
```

As is evident from the above, I had to maintain my own state of selected columns and then manipulate `cellRanges` directly within my own code and invoking `dispatchChangedEvent` on the `rangeController`. Not great, but it is a workaround for the time being.

Having said that, I think that this ought to be native functionality of the API.

**Comment by seanlandsman** [comment]
Thanks for the feedback - I see you want to submit a PR for this, but in the meantime I'll discuss this with the team and get back to you

thanks

**Comment by ricazhang** [comment]
Just wondering whether this feature ever got added? Or what happened to the PR that zealoushacker submitted?

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
