### ISSUE TITLE
Default Style Location Needs to be Top Not Bottom

### ISSUE THREAD

**Issue by ddelella** [ag-grid/ag-grid-enterprise#129]
[ ] bug report
[X] feature request
[ ] support request

OS: Windows 10
Browser: Any
Version: 11.0.0
Language: ES5

When rendered to html the ag-grid JavaScript file is insert several <style> blocks into the <head> tag.  These styles are being inserted at the bottom of the <head> tag by default.  The problem with this approach is that there is no way to override these styles and maintain good html design practices.  Good practice says that all style sheets should be imported in the header.  As a result the ag-grid styles will always be below these imports.  No users customized styles can override these except ones loaded in the <body> tag.  

The request is to change this option to default to the top of the <head> tag, similar to Angular UI libraries.

**Comment by ddelella** [comment]
An alternative would be to simply provide the css files in the dist folder.  This is more standard than forcing the style addition to the <head> tag.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
