### ISSUE TITLE
Context menu event not firing on full width group rows

### ISSUE THREAD

**Issue by R4DIC4L** [ag-grid/ag-grid-enterprise#130]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When right clicking on a full width group row (groupUseEntireRow=true), the getContextMenuItems method is not called. Instead, the browser context menu is shown. This can also be seen in the ag-grid example [here](https://www.ag-grid.com/javascript-grid-grouping/#fullWidthRows).

**Expected behavior**
The getContextMenuItems method should be called for full width group rows as it is called for group rows that don't use the entire row to allow for a context menu.

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 11.0.0

* **Browser:**
Chrome/59.0.3071.115
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Edge/40.15063 EdgeHTML/15.15063
IE/11.413.15063

* **Language:** Javascript ES6, React

**Comment by seanlandsman** [comment]
Hi,

I've raised a new issue for this our side (AG-596). We'll update this thread as soon as  we have any updates.

thanks for reporting this

**Comment by chaitanyapai6169** [comment]
Can anyone please update on this. I am getting the same issue

**Comment by makinggoodsoftware** [comment]
Lucky timing to ask for it, literally was fixed hours ago, will be available next release eta 3-5 weeks

**Comment by JohnMasterson** [comment]
Just to confirm this was included in Version 15 which was released last week.

https://www.ag-grid.com/ag-grid-blog-15-0-0/

Regards, 

John
