### ISSUE TITLE
TypeScript types included but not declared in package.json

### ISSUE THREAD

**Issue by amirburbea** [ag-grid/ag-grid-enterprise#136]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

types line not exposed in package.json.  Importing `ag-grid-enterprise` from my TS application requires importing it as `import * as agGridEnterprise from 'ag-grid-enterprise/main'`.

**Expected behavior**

I should be able to import directly from the package like `import * as agGridEnterprise from 'ag-grid-enterprise'`.

Simply adding `"types": "main.d.ts"` to the package.json would fix this

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 12.0.X
* **Language:** TypeScript 2.4

**Comment by seanlandsman** [comment]
This has been added - it will be available in our next release

thanks
