### ISSUE TITLE
Single Click event getting triggered in Double Click

### ISSUE THREAD

**Issue by vbiarunp** [ag-grid/ag-grid-enterprise#137]
I used "onRowSelected" and  "onRowDoubleClicked" in my ag-grid and Both are working fine seperately.
 When i use them together, then my onRowDoubleClicked functions is not getting triggered when double click is made instead the onRowSelected function is called. 

Here is the issue link https://plnkr.co/edit/dV0IgtJyjdn5TdIgQj1U?p=preview

**Current behavior**
    onRowSelected event called instead onRowDoubleClicked event in double click

**Expected behavior**
   onRowSelected event should be called only on single click

**Please tell us about your environment:**
   Windows 8.1

**Comment by seanlandsman** [comment]
If you change your plunker to a console.log (from alert) you'll see that both events are called

This is correct and expected behaviour - thanks
