### ISSUE TITLE
Floating filter is grayed out in Enterprise version

### ISSUE THREAD

**Issue by mpetkov** [ag-grid/ag-grid-enterprise#138]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Floating filter is grayed out in Enterprise version only (It works fine in free version)

**Expected behavior**
Floating filter should work in Enterprise edition.

**Minimal reproduction of the problem with instructions**
Enterprise version the filter is off:  http://plnkr.co/edit/EptjaL?p=preview
Free version the filter works: http://plnkr.co/edit/RovFLBOA14swOR3XTW33?p=preview

* **ag-Grid-Enterprise version:** 12.0.2

**Comment by seanlandsman** [comment]
You only need either ag-grid or ag-grid-enterprise when using the bundled version.

Remove ag-grid.js from the enterprise version and it should work as expected

thanks

**Comment by mpetkov** [comment]
@seanlandsman Thank you for the reply.  Here is a version where I removed the ag-grid.js file but it still doesn't work:
http://plnkr.co/edit/zdkTpT?p=preview

**Comment by seanlandsman** [comment]
@mpetkov the enterprise version defaults to a set filter, and set filters arent editable. That would explain the difference here

I'll update the docs to reflect this.

Going forward I suggest you post to the members forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5 where we'll be able to assist you with support queries

**Comment by ghacheniour** [comment]
@seanlandsman is there a way to just activate specific feature of ag-grid-enterprise?

**Comment by seanlandsman** [comment]
@ghacheniour It depends on the feature. Some features are enabled with flags for examples (charting is an example)

You would have to refer to the docs in the area your interested in to see if it can be enabled/disabled
