### ISSUE TITLE
Expand icon for pivot columns is hidden when text in column is greater than width

### ISSUE THREAD

**Issue by paronne** [ag-grid/ag-grid-enterprise#139]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The icon to expand a pivot column is not always visible. Since is aligned right, if the column text value is too long the expand icon may be hidden. 

**Expected behavior**

The expand icon should be aligned left so to be always visible as default or at least have the possibility to set alignment of the expand icon to the left.

**Minimal reproduction of the problem with instructions**

Go in pivot mode and add at least 2 columns as pivot columns; the first pivot column will have an expand icon. Reduce the width of the column until the expand icon disappear.

**What is the motivation / use case for changing the behavior?**

As user it takes an extra effort to expand pivot columns, i need first to resize the column until the expand icon is visible and then i would be able to expand. Also increasing the column's width reduce the available horizontal space; the user experience can be greatly improved having the expand icon on the left (therefore always visible).

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 12.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
