### ISSUE TITLE
Column's maxWidth is exceeded when width is not specified

### ISSUE THREAD

**Issue by paronne** [ag-grid/ag-grid-enterprise#140]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Column's maxWidth is exceeded when width is not specified. columns are rendered with a default width greater than maxWidth. 
When resizing the column or force the column to auto size or setColumnsToFit() is executed, it behaves correctly and does not exceed the maxWidth.

**Expected behavior**

Column's maxWidth should never be exceeded.

**Minimal reproduction of the problem with instructions**

Render a grid having column with maxWidth=50 without forcing a setColumnsToFit(), the columns will be rendered by default with a greater width than 50px

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 12.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide with a plunkr for this bug, we only take bugs from github if they have a reproducible scenario

Thanks

===============

Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
