### ISSUE TITLE
Grid in fullscreen mode collapses to tool panel width in Chrome

### ISSUE THREAD

**Issue by jcsjcs** [ag-grid/ag-grid-enterprise#141]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After putting the grid div into fullscreen mode, when the tool panel is opened, the display shrinks to the width of the tool panel and the rest of the grid is hidden.
This behaves correctly in Firefox but not in Chrome, I haven't tested any other browsers.

**Expected behavior**
The tool panel should open within the grid as in normal mode and the grid should maintain its width.

**Minimal reproduction of the problem with instructions**
Open any example grid in a new tab in Google Chrome - e.g. https://ag-grid.com/javascript-grid-column-spanning/exampleColumnSpanning.html
Open the console.
Type:
```
domGrid = document.getElementById('myGrid')
domGrid.webkitRequestFullscreen()
```
With the grid in fullscreen mode, open the tool panel - the display drops each column in turn until only the tool panel remains.

**What is the motivation / use case for changing the behavior?**
Opening a grid in fullscreen mode is often useful and the grid should be usable in this mode.

**Please tell us about your environment:**
Ubuntu 16.04, Google Chrome  60.0.3112.113.

* **ag-Grid-Enterprise version:** 2.0.X
12.0.2.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 60.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES5

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this. I've raised AG-718 our side to track this - you can view its progress on our pipeline page here: https://www.ag-grid.com/ag-grid-pipeline/

We'll update this thread with updates as soon as we have any.

thanks

**Comment by makinggoodsoftware** [comment]
Seems to be fixed now

**Comment by jcsjcs** [comment]
This problem is still observable at https://ag-grid.com/javascript-grid-column-spanning/exampleColumnSpanning.html which is running 14.2.0.
(Google Chrome Version 62.0.3202.94)

**Comment by makinggoodsoftware** [comment]
I just tried this on a Mac and is working for me... Is this on Windows?

**Comment by jcsjcs** [comment]
No, this is on Linux (Ubuntu 16.04).

**Comment by jcsjcs** [comment]
This problem is still observable with version 15.
In Chrome, go to https://ag-grid.com/javascript-grid-column-spanning/exampleColumnSpanning.html
Open the console and type in:
```
domGrid = document.getElementById('myGrid')
domGrid.webkitRequestFullscreen()
```
Then open the tool panel from any header and the grid collapses.
Note: you do not get the same behaviour if you just make the page fullscreen - only when you make the grid div ('#myGrid') fullscreen.
