### ISSUE TITLE
Clicking outside of richSelect window selects the hovered select option

### ISSUE THREAD

**Issue by jmoore315** [ag-grid/ag-grid-enterprise#144]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When the richSelect editor is open, if a new value is highlighted and then the user clicks outside of the select window, the hovered item is selected. This causes unintentional data changes

**Expected behavior**
Clicking outside of the richSelect window should close the window without changing the original value

**Minimal reproduction of the problem with instructions**

Please see explanations above - this is reproducable with any grid using 'richSelect' cell editor

**What is the motivation / use case for changing the behavior?**
Causes unintentional data changes

**Please tell us about your environment:**
OSX 10.12.6 | node v 8.4

* **ag-Grid-Enterprise version:** 13

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome v 60

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by seanlandsman** [comment]
Hi,

If you are an Enterprise customer (or are Evaluating ag-Grid Enterprise) and wish to report a Bug or raise a new Feature Request please do so on our [Members Forum](https://ag-grid.com/forum/forumdisplay.php?fid=5).

To Sign Up:
Send an email to accounts@ag-grid.com with your license key

thanks
