### ISSUE TITLE
No way to specify "expanded" flag (for ColumnSelect) in ColGroupDef

### ISSUE THREAD

**Issue by cpboyd** [ag-grid/ag-grid-enterprise#146]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Per [RenderGroup L48](https://github.com/ag-grid/ag-grid-enterprise/blob/master/src/toolPanel/columnsSelect/renderedGroup.ts#L48), this defaults to true.

All groups start out expanded in the Column Select, regardless of whether any columns within the group are visible or not.

**Expected behavior**

It'd be nice if it were possible to simply set the initial/default expanded state within the column definitions.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

My client would like to have certain groups default to collapsed in the Column Select, specifically groups that have no columns selected.

Additionally, it might be nice if there were a way to hook-in to the group select callback to change the expanded flag.  (e.g. expand the group when checked or collapse the group when unchecked)

**Please tell us about your environment:**

**OS:** Windows
**IDE:** VS Code
**Package Manager:** Yarn

* **ag-Grid-Enterprise version:** 2.0.X

* **Browser:** All

* **Language:** All

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
