### ISSUE TITLE
Context Menu Does Not Fire 'open/close' Events

### ISSUE THREAD

**Issue by michaelvashchinsky** [ag-grid/ag-grid-enterprise#150]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Right-click opens a context menu (when `getContextMenuItems()`) returns a list of menu items, but there are no events that can tell the programmer that the context menu was opened/closed.

**Expected behavior**
When context menu opens there should be `contextMenuOpened` (or similar) event fired.
When context menu closes there should be `contextMenuClosed` (or similar) event fired.

**Minimal reproduction of the problem with instructions**
No need to reproduce, there is nothing in the docs about context menu events.

**What is the motivation / use case for changing the behavior?**
The programmer may have to do something on context menu opens, and when it closes (unselect right-clicked-selected row).

**Please tell us about your environment:**
osSierra, Play!.

* **ag-Grid-Enterprise version:** 2.0.X
v7.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
