### ISSUE TITLE
Error in RichSelect after upgrade to ag-grid 14.2.0

### ISSUE THREAD

**Issue by usood1** [ag-grid/ag-grid-enterprise#154]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
For columns that have richSelect specified as below, getting below error on double-click in the select box. Also nothing is displayed in the select box:

var FEE_CATEGORIES = ['Value1', 'Value2', 'Value3']
{headerName: 'Fee Category',field: 'feeCategory', cellEditor: 'richSelect',  cellEditorParams: { values: FEE_CATEGORIES } }

Error:
Uncaught TypeError: Cannot read property 'then' of null
    at RichSelectRow.populateWithRenderer (richSelectRow.js:63)
    at RichSelectRow.setState (richSelectRow.js:43)
    at RichSelectCellEditor.createRowComponent (richSelectCellEditor.js:137)
    at VirtualList.insertRow (virtualList.js:139)
    at VirtualList.ensureRowsRendered (virtualList.js:117)
    at VirtualList.drawVirtualRows (virtualList.js:102)
    at VirtualList.refresh (virtualList.js:91)
    at RichSelectCellEditor.afterGuiAttached (richSelectCellEditor.js:161)
    at PopupEditorWrapper.afterGuiAttached (popupEditorWrapper.js:79)
    at CellComp.afterCellEditorCreated (cellComp.js:806)

**Expected behavior**
The error should not occur

**Minimal reproduction of the problem with instructions**
Create a grid with a richSelect cell using ag-grid-enterprise 14.2.0

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
ag-grid, ag-grid-enterprise and ag-grid-react: version 14.2.0
react version 15.3.2
Issue started when we upgraded to ag-grid 14.2.0

* **Browser:** Chrome 

* **Language:** [ES6/7 | ES5]

**Comment by makinggoodsoftware** [comment]
Hi,

Can you provide with a plunkr for this bug, we only take bugs from github if they have a reproducible scenario

Thanks

===============

Hi,

Thank you for raising this issue for us, at this moment we are reviewing how we process Feature Requests/questions that come through from GitHub.

As I am sure you are aware, we offer two products:

ag-Grid - this is entirely free to use in line with our MIT license
ag-Grid Enterprise - our commercial version which funds the development of both versions.

We currently have a very full pipeline of work which can be viewed here: https://www.ag-grid.com/ag-grid-pipeline/

This will be our priority for the coming months and as a result, we don’t have capacity to take feature requests/questions from GitHub.

We will do a periodic review of GitHub issues for any bugs raised and these can also be tracked on our pipeline page.

Thanks for your understanding.
ag-Grid Team.
