### ISSUE TITLE
Export to excel - date formats

### ISSUE THREAD

**Issue by bondib** [ag-grid/ag-grid-enterprise#156]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently, you can't export to excel date data - but only as string values.
This means using dates in excel is impossible for non advanced users.

**Expected behavior**

To have a way to export date values to excel so excel recognizes the values as DATE values and not strings.

**Minimal reproduction of the problem with instructions**

Export to excel from the grid a column that contains date values.
Open excel - and see that it's considered as string.

**What is the motivation / use case for changing the behavior?**

As described above...

**Please tell us about your environment:**

All env.

* **ag-Grid-Enterprise version:** 15.0

Yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by makinggoodsoftware** [comment]
Hi,

Have you seen our docs for exporting dates...

https://www.ag-grid.com/javascript-grid-excel/#example-excel-data-types


===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by bondib** [comment]
I have seen the documentation and this functionality was missing.
It seems you've added support for dateTime starting v14.0 
I'll check if it works.

Thanks,
benjamin

**Comment by bondib** [comment]
OK - so I just checked it out.
Almost perfect - the only problem is with the following:

`When using dataType: 'dateTime' Excel doesn't format the resultant value, in this example it shows 39923. You need to add the formatting inside Excel`

**Comment by nealYangVic** [comment]
Agree, the 39923 format really weird, can we improve this to able to handle default format

**Comment by Ruud-cb** [comment]
You can set a default format by adding:

`dateExcelStyle.numberFormat = { format : 'HH:mm dd-MM-yyyy'}`
