### ISSUE TITLE
Ag-Grid dep should be external

### ISSUE THREAD

**Issue by DominicTobias** [ag-grid/ag-grid-enterprise#168]
Hi,

You should have `ag-grid` listed in devDependencies as well as peer ones and your webpack config should have:

```js
externals: {
  'ag-grid': 'ag-grid',
}
```

This minified bundle size is **1.75mb** on top of ag-grid which is already as large. Even one package alone is the largest package I have ever used in the javascript ecosystem. The enterprise version of AG weighs in at **~4mb minified, 13mb unminified**, and crashes Chrome inspector on a 64GB RAM machine in the code view! I would also think this much JS to parse is going to slow down older parsing engines in IE.

**Comment by JabbyPanda** [comment]
Now I know why my Chrome inspector crashes so often...

**Comment by seanlandsman** [comment]
Hi

The enterprise version includes ag-grid-community - it's not something that is considered external when we bundle the app.

ie when you use the enterprise bundle it includes ag-grid-community - you don't need to include this too.

If you're including both this might explain why your bundle sizes are so big - I'm not sure where the 4mb figure comes from?

In any event I hope this helps. We are looking at modularising the codebase this year as well as support tree shaking, both of which should allow users to cherry pick the features they need as well as reduce bundle sizes

**Comment by DominicTobias** [comment]
This is what happens when you don't directly install ag-community

![enterprise](https://user-images.githubusercontent.com/760314/53335420-58d3e180-38f3-11e9-86bd-f7d85ed80e96.jpg)

**Comment by seanlandsman** [comment]
There appears to be a misunderstanding here.

I was talking about the bundled version we supply:

For the community edition:
https://github.com/ag-grid/ag-grid/tree/master/packages/ag-grid-community/dist
(ag-grid-community.XXX.js)

For the enterprise edition: 
https://github.com/ag-grid/ag-grid/tree/master/packages/ag-grid-enterprise/dist
(ag-grid-enterprise.XXX.js)

In the latter case the community code is already included and so doesn't need to be bundled twice.

From what you're saying I'm assuming you're doing the bundling yourself and if this is the case my point still stands - if you're using enterprise you need to include the community code. The enterprise builds on top of - and depends on - the community code. It is not external/separate - unless you're somehow bundling both separately for some reason, but this won't be the common use case.

Perhaps you can expand on how you're bundling your code - I can't see how you're getting to the bundle sizes you describe (~4mb minified, 13mb unminified)

**Comment by DominicTobias** [comment]
@seanlandsman thanks I updated my original issue comment to not spread confusion. It turns it this was how AG was being wrapped up and when I stopped using our company wrapper it drastically reduced the size (to about 1mb minified)

**Comment by matchifang** [comment]
@seanlandsman I saw your comment on how I don't need community version if I already have the enterprise version.
I'm using enterprise 21.2.2 and I get errors when I remove ag-grid-community (npm uninstall)
The errors are usually something along the line of
`node_modules/ag-grid-enterprise/dist/lib/something.d.ts error TS2307: Cannot find module 'ag-grid-community'`

**Comment by seanlandsman** [comment]
@matchifang I was referring to the UMD bundles when I said enterprise contains community (i.e. ag-grid-enterprise.XXX.js)

If you're using the actual npm packages or modules then you need to include community as well as enterprise.

To be clear - UMD bundles (ie you're probably not using a bundler like webpack in your application) are self contained and contain everything you need. npm packages are different and in that case you need to specifiy both community and enterprise

thanks
