### ISSUE TITLE
getDataAsExcel: not working with xlsx read:  TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sahildev-jd** [ag-grid/ag-grid-enterprise#208]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm trying to read the xml that i'm getting from this.gridOptions.api.getDataAsExcel() using 
XLSX.read(content, {type: 'string'}) but its giving error. This used to work and give me a workbook in v17.1.1 . Can you please let me know what I need to do inorder to parse the xml thats getting generated.?
Error I'm getting:  **TypeError: Cannot read property '0' of undefined**

**Expected behavior**
It should work with XLSX.read(content, {type: 'string'})

**Minimal reproduction of the problem with instructions**
These are my params while exporting.
{
                     skipHeader: false,
                     fileName: 'Plan_Rpt' + '.xlsx',
                     sheetName: 'Cluster Summary',
                    suppressTextAsCDATA: true,
                     columnGroups: true,
                     allColumns: true,
                     customHeader: [
                         [{
                             data: {
                                 type: 'String',
                                 value: 'PLAN SUMMARY'
                             }
                         }]
                     ],
                   exportMode: 'xlsx'
                }
**What is the motivation / use case for changing the behavior?**
The reason I need to use getDataAsExcel is that i want to concatenate the data from various grids and export it into one Excel (else I'd've used exportDataAsExcel).

**Please tell us about your environment:**
MacOS, IntelliJ Idea Ulitmate 2018.3, npm, bower

* **ag-Grid-Enterprise version:** 19.1.4

* **Browser:** 
Chrome

* **Language:** all

Thanks in advance :)

**Comment by Elcaten** [comment]
I also encountered this problem, do you by any chance happen to now any workaround? Is there a way to export a whole workbook instead of just a single worksheet?

**Comment by gportela85** [comment]
As this is an enterprise feature, please file a BUG report using the support channel.

**Comment by sahildev-jd** [comment]
@Elcaten I worked it around getDataAsCsv. Mostly rest of the things remained the same.
