### ISSUE TITLE
Dynamic asynchronous context menu 

### ISSUE THREAD

**Issue by vijayanandof** [ag-grid/ag-grid-enterprise#223]
**I'm submitting an idea/Enhancement ** 
```
[ X] I want dynamic async context menus, which make api call and return menus. 
It is not possible to do with existing functionalities. 
```

**Current behavior**
On right click of the Ag-Grid we are able to get context menu, but unable to have dynamic menu items that are based on row node's data[Data got through API call].

**Expected behavior**
Dynamic menus should be possible, add a prop in list and it should be considered as dynamic async menu list, it should give a loading indicator till it fetches the items in API call.

**Minimal reproduction of the problem with instructions**
https://next.plnkr.co/edit/lMqw5MZSUrmqSToj

**What is the motivation / use case for changing the behavior?**
User will be able to easy perform actions, instead of some other workflow implementation.

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 19.0.0

Done

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by LuzTn** [comment]
Have you found a solution please?
I need the same functionality...

**Comment by LuzTn** [comment]
@seanlandsman is there a way to get this feature?

**Comment by seanlandsman** [comment]
@LuzTn I'm afraid not at this time

Please note that this repo is deprecated - you should raise issues here https://github.com/ag-grid/ag-grid instead

thanks
