### ISSUE TITLE
How to set tool tip on a checkbox column in a row

### ISSUE THREAD

**Issue by ThotaAshok** [ag-grid/ag-grid-enterprise#230]
I am using ag-grid enterprise and i have below code. If a condition is satisfied all i want to do is show an icon with a tool tip. I tried, but not working. How to show a tool tip on hover of a a cell on a row of grid?

, cellRenderer:
                        function (params) {
                            if (null === vm.searchResult) { 
                                if (params.node.data.Type === 1) {
                                    var divElement = document.createElement('div');
                                    divElement.innerHTML = '<i class="icon block"></i><span class="sr-only">My custom Test message.</span>';                                    
                                    divElement.onmouseover = 'My custom Test message.';
                                    divElement.onfocus = 'My custom Test message.';
                                    return divElement;
                                }
                            }
                            else {
                                return params.value;
                            }
                        }

**Comment by ThotaAshok** [comment]
Could somebody respond on this. Or give me the link to a sample where I can see how to use tooltip.

**Comment by gportela85** [comment]
@ThotaAshok Please, contact ag-Grid's support using ZenDesk.
