### ISSUE TITLE
applyTransaction({addIndex: 0, add: [newRow]}) inserts at the end of the grid rather than the beginning

### ISSUE THREAD

**Issue by willh33** [ag-grid/ag-grid-enterprise#253]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Calling applyTransaction, passing in the index to place the row doesn't 
I'm trying to insert a row at a specific index on the grid, but it always sticks the new row at the end of the grid

**Expected behavior**

The row should be inserted at the specified index rather than at the end of the row

**Minimal reproduction of the problem with instructions**
Steps to reproduce:
Here is a plunkr showcasing the issue: https://plnkr.co/edit/P2bqJRibGiQf9LH8
Comment out line 9 in index.jsx where it's importing 'ag-grid-enterprise', and it will insert correctly at the specified index

**What is the motivation / use case for changing the behavior?**

My users need to be able to insert rows in specific places on the grid

**Please tell us about your environment:**

OS: MacOs
ID: Webstorm
Package Manager: Yarn

* **ag-Grid-Enterprise version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Only tried in Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gportela85** [comment]
ag-Grid does not offer support on github, however, if you take a look at the console.log output, you will see that passing rowIndex to `applyBatch` has been deprecated.

**Comment by willh33** [comment]
Is there a way that's not deprecated? How do I place rows at a specific index?
