### ISSUE TITLE
Angular Build WARNING -  depends on 'ag-grid-enterprise'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### ISSUE THREAD

**Issue by ofirrifo** [ag-grid/ag-grid-enterprise#256]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After I upgrade to angular 10 I execute ng build and I get this warning 
 depends on 'ag-grid-enterprise'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Expected behavior**
Not get the above warning

**Minimal reproduction of the problem with instructions**
upgrade angular project from 9 to 10 that use 'ag-grid-enterprise' and run build

**Please tell us about your environment:**
Webstorm

* **ag-Grid-Enterprise version:** 2.0.X
   "ag-grid-angular": "^23.2.1",
    "ag-grid-community": "^23.2.1",
    "ag-grid-enterprise": "^23.2.1",

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by rwagstaff** [comment]
Hi 

I had the same issue when moving to angular 10

WARNING in ...\main.ts depends on 'ag-grid-enterprise'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

	"ag-grid-angular": "^23.2.1",
    "ag-grid-community": "^23.2.1",
    "ag-grid-enterprise": "^23.2.1",

As I was importing LicenseManager in main.ts with statement

`import { LicenseManager } from 'ag-grid-enterprise';`

To fix I changed my package.json to

    "@ag-grid-community/core": "^23.2.1",
    "@ag-grid-enterprise/core": "^23.2.1",

Then in main.ts I changed the License Manage import to 

`import { LicenseManager } from '@ag-grid-enterprise/core';`

More information on ag-grid modules here https://www.ag-grid.com/javascript-grid-modules/

**Comment by joshstrohminger** [comment]
I also ended up switching to using modules to remedy this in Angular 11 and it cut down my final bundle size because I didn't need every module. One difference though is that I also had to change my reference from 

```"ag-grid-angular": "^25.3.0"```

to

```"@ag-grid-community/angular": "^25.3.0"```

and to register the modules I was using site-wide in the same place I was entering my license key. See https://www.ag-grid.com/angular-data-grid/modules/

**Comment by seanlandsman** [comment]
Hi - this issue can be tracked by AG-6270, but I can tell you this has been fixed and will be available in our next release.

thanks for reporting this

**Comment by StephenCooper** [comment]
AG Grid v28 has now been released so please upgrade to avoid this issue. 

If you are using Angular v8-11 you will need to switch to our legacy packages for v28. For more details on this see this [post](https://blog.ag-grid.com/upcoming-changes-to-ag-grid-angular-in-v28/) and the [Angular Compatibility](https://ag-grid.com/angular-data-grid/angular-compatibility/)  doc page.
