### ISSUE TITLE
[node] Add ag-grid as a regular dependency in package.json

### ISSUE THREAD

**Issue by BrandonNoad** [ag-grid/ag-grid-enterprise#70]
Right now, package.json has:

```
"peerDependencies": {
    "ag-grid": "6.0.x"
  }
```

But npm@3 doesn't download peer dependencies (http://blog.npmjs.org/post/110924823920/npm-weekly-5).

I need to install 2 different versions of ag-grid in my project. I have a bunch of grids using ag-grid v3.3.3, and I don't have time to make them compatible with the v6.0.x at the moment. But, I want to build another grid that takes advantage of the new features. This new grid is being built inside a "plugin" with its own install root (https://github.com/npm/npm/issues/5499#issuecomment-76107537).

So the package.json for my main project has:

```
"dependencies": {
    "ag-grid": "^3.3.3"
  }
```

And the package.json of my plugin has:

```
"dependencies": {
    "ag-grid": "^6.0.1",
    "ag-grid-enterprise": "^6.0.1"
  }
```

When I run npm install on the main project, the node_modules folder ends up like this:

node_modules
    ag-grid (v3.3.3)
    ag-grid-enterprise (v6.0.1)
    my-plugin
        node_modules
            ag-grid (v6.0.1)

Since npm@3 flattens the node_modules where it can, when I require ag-grid-enterprise from my plugin, I end up with an error: 

`renderedGroup.js:17 Uncaught TypeError: Cannot read property 'getInstance' of undefined`

This error occurs, because ag-grid-enterprise requires ag-grid, but in my situation, it ends up with v3.3.3 instead of v6.0.1.

If ag-grid-enterprise had a dependency on ag-grid, then there would be a node_modules folder inside the ag-grid-enterprise package with ag-grid v6.0.1 in it, which would resolve the error.

In the meantime, as a workaround, I think I can depend on an older version of ag-grid-enterprise in my main project, which will force ag-grid-enterprise (v6.0.1) to install nested alongside ag-grid (v6.0.1). But it would be nice not to have to do that.

https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/

Thanks!

**Comment by ceolter** [comment]
thank you for raising. i've added this to my 'to do' list. i'm slow to change things around the dependencies without fully understanding what i am doing, as it's easy to get it working locally, but mess it up for others, given all the different scenarios one needs to consider. so i will put some time aside to read into this properly and to the correct thing.

ps i think this will take a few hours for me, and the next months i'm up the walls (getting married) so may not be in the coming weeks. given you have a workaround, i take it this is acceptable.

**Comment by ceolter** [comment]
tracked by AG-181

**Comment by seanlandsman** [comment]
Hi,

This has now been done - it will be available in our next release.

thanks
