### ISSUE TITLE
[clipboard] Clipboard support to copy other formats than text.

### ISSUE THREAD

**Issue by jarismar** [ag-grid/ag-grid-enterprise#94]
Today clipboardService only copy text (tab delimited) to the clipboard.

The new clipboardData API (supported by all major browsers) allows to set formatted data directly to the clipboard ([See this guide](https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/)).

The idea is to identify if the new API is present, then add specific formatted data to clipboard, at least **text/plain** and **text/html** should be present.

What I need is to have an html table right after copying data from ag-grid and pasting on MSOffice programs (outlook, excel, msword). Today I have to manually format the text as a table after copying data from ag-grid.

I will try to implement this and propose a pull request soon. Just curious to know if something like this is not already in course.

**Comment by ceolter** [comment]
this one is news to me. thanks for bringing it to our attention. if you would like to propose a PR it would be appreciated, however we do scrutinise all PR's so bear with us if it takes us a time to get to yours.

**Comment by ceolter** [comment]
tracked by AG-180
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment]
Hi we won't do this one given its complexity

**Comment by jarismar** [comment]
I'm sorry but I disagree.
If you look into the original commit, the introduced code does basically 2 things:
1. It constructs an HTML table from the selection range (the htmlFormatter method).
2. It calls **event.clipboardData.setData('text/html', this.htmlFormatter(dataObj))**; to send text/html to clipboard.
I've been using this solution on my ag-grid fork. The only reason I didn't submitted a PR yet is because I understand we need to expose an API, so that client code can customize the style of the html table sent do clipboard.
I'll be back with a PR as soon as possible.
